CREATE DATABASE thelasthope CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
USE thelasthope;


CREATE TABLE users (
id INT AUTO_INCREMENT PRIMARY KEY,
username VARCHAR(100) UNIQUE NOT NULL,
password_hash VARCHAR(255) NOT NULL,
email VARCHAR(255),
role ENUM('admin','editor') DEFAULT 'editor',
created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);


CREATE TABLE teams (
id INT AUTO_INCREMENT PRIMARY KEY,
name VARCHAR(150) NOT NULL,
tag VARCHAR(20),
logo VARCHAR(255),
country VARCHAR(100),
created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
updated_at TIMESTAMP NULL
);


CREATE TABLE players (
id INT AUTO_INCREMENT PRIMARY KEY,
team_id INT NULL,
nickname VARCHAR(100) NOT NULL,
real_name VARCHAR(150),
avatar VARCHAR(255),
role VARCHAR(100),
nationality VARCHAR(100),
joined DATE NULL,
created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
updated_at TIMESTAMP NULL,
FOREIGN KEY (team_id) REFERENCES teams(id) ON DELETE SET NULL
);


CREATE TABLE competitions (
id INT AUTO_INCREMENT PRIMARY KEY,
name VARCHAR(200) NOT NULL,
slug VARCHAR(200) UNIQUE NOT NULL,
start_date DATE,
end_date DATE,
description TEXT,
created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);


CREATE TABLE matches (
id INT AUTO_INCREMENT PRIMARY KEY,
competition_id INT NULL,
match_date DATETIME,
home_team_id INT,
away_team_id INT,
home_score INT DEFAULT 0,
away_score INT DEFAULT 0,
status ENUM('scheduled','live','finished','cancelled') DEFAULT 'scheduled',
notes TEXT,
created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
FOREIGN KEY (competition_id) REFERENCES competitions(id) ON DELETE SET NULL,
FOREIGN KEY (home_team_id) REFERENCES teams(id) ON DELETE CASCADE,
FOREIGN KEY (away_team_id) REFERENCES teams(id) ON DELETE CASCADE
);


CREATE TABLE player_match_stats (
id INT AUTO_INCREMENT PRIMARY KEY,
match_id INT NOT NULL,
player_id INT NOT NULL,
team_id INT NOT NULL,
kills INT DEFAULT 0,
deaths INT DEFAULT 0,
assists INT DEFAULT 0,
score FLOAT DEFAULT 0,
additional JSON NULL,
created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
FOREIGN KEY (match_id) REFERENCES matches(id) ON DELETE CASCADE,
FOREIGN KEY (player_id) REFERENCES players(id) ON DELETE CASCADE,
FOREIGN KEY (team_id) REFERENCES teams(id) ON DELETE CASCADE
);
